import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 6,
    marginVertical: 0,
    marginHorizontal: 0,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  input: {
    fontSize: 16,
    color: "#333",
    minHeight: 0,
    textAlignVertical: "top",
    marginBottom: 16,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  counter: {
    fontSize: 14,
    color: "#666",
  },
  submitButton: {
    backgroundColor: "#007AFF",
    borderRadius: 24,
    width: 48,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
  },
  submitButtonDisabled: {
    backgroundColor: "#f0f0f0",
  },
  imageButton: {
    backgroundColor: "#f0f0f0",
    borderRadius: 24,
    width: 48,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
  },
  imagePreview: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    paddingLeft: 5,
    paddingTop: 5,
  },
  imageContainer: {
    position: "relative",
    width: 100,
    height: 100,
    borderRadius: 10,
    marginRight: 12,
  },
  previewImage: {
    width: "100%",
    height: "100%",
    borderRadius: 10,
    objectFit: "cover",
  },
  removeImage: {
    position: "absolute",
    top: "50%",
    right: "50%",
    transform: [{ translateX: "50%" }, { translateY: "-50%" }],
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    borderRadius: 24,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
});
